### ISSUE TITLE
Fails sporadically in Ruby 1.9.2

### ISSUE THREAD

**Issue by pmahoney** [gcao/aspect4r#34]
I have this test example:

```
$ cat aspect4r_bug.rb
require 'aspect4r'

class Klass
  include Aspect4r

  class << self
    around :test do |*args, &block|
      block.call(*args)
    end

    def test(*args)
      puts "test called with args: #{args}"
    end
  end
end

Klass.test('arg')
```

When I run with Ruby 1.8.7, everything works OK: (also works ok in Rubinius 1.2.5dev)

```
$ while true; do ruby1.8.7 -r rubygems aspect4r_bug.rb; done
test called with args: arg
test called with args: arg
...
```

But in Ruby 1.9.2 (and 1.9.1), it fails sporadically:

```
$ while true; do ruby1.9.2 -r rubygems aspect4r_bug.rb; done
test called with args: ["arg"]
test called with args: ["arg"]
/Users/pat/.rvm/gems/ruby-1.9.2-p180/gems/aspect4r-0.9.1/lib/aspect4r/helper.rb:9:in `block in create_method_with_advices': undefined local variable or method `a4r_around_0_' for Klass:Class (NameError)
    from aspect4r_bug.rb:17:in `<main>'
```
